name: cuttle

services:
  database:
    container_name: database
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cuttle
      - POSTGRES_USER=cuttlesworth
      - POSTGRES_PASSWORD=p4ssw0rd!
    volumes:
      - ./data/pgdata:/var/lib/postgresql
    restart: always

  app:
    container_name: cuttle-app
    restart: unless-stopped
    environment:
      - NODE_ENV=staging
      - CUTTLE_DOCKERIZED=true
      - DATABASE_URL=postgresql://cuttlesworth:p4ssw0rd!@database:5432/cuttle
      - VITE_API_URL=http://localhost:1337
      - VITE_BUILD_OUTPUT=assets
      - CUTTLE_ENABLE_CUTTHROAT=true
      - CUTTHROAT_AUTO_RUN_MIGRATIONS=true
      - RUST_BIND_ADDR=127.0.0.1:4000
      - JS_INTERNAL_BASE_URL=http://127.0.0.1:1337
      - CUTTLE_RUST_URL=http://127.0.0.1:4000
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
      - "1337:1337"
    depends_on:
      - database
