[package]
name = "cutthroat_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8.5"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"

[dev-dependencies]
pretty_assertions = "1.4.1"
